-- Wrap auth.uid()/current_setting() in RLS policy predicates in (select ...) so
-- Postgres evaluates each once per statement (an InitPlan) instead of once per row --
-- the Supabase-documented RLS perf pattern. Covers USING and WITH CHECK. Predicate-
-- equivalent (row visibility unchanged). Generated by 'pgrls fix --rule PERF001'
-- (pgrls 0.44.0) and verified on Postgres 16 (PERF001 -> 0).

-- [PERF001] Wrap auth function call(s) in policy 'Users can read own profile' on public.profiles so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can read own profile" ON public.profiles
    USING ((SELECT auth.uid()) = id);

-- [PERF001] Wrap auth function call(s) in policy 'Users can update own profile' on public.profiles so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can update own profile" ON public.profiles
    USING ((SELECT auth.uid()) = id)
    WITH CHECK ((SELECT auth.uid()) = id);

-- [PERF001] Wrap auth function call(s) in policy 'Owner can delete their shared mcp' on public.shared_mcp_configs so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Owner can delete their shared mcp" ON public.shared_mcp_configs
    USING (owner_id = (SELECT auth.uid()));

-- [PERF001] Wrap auth function call(s) in policy 'Owner can update their shared mcp' on public.shared_mcp_configs so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Owner can update their shared mcp" ON public.shared_mcp_configs
    USING (owner_id = (SELECT auth.uid()));

-- [PERF001] Wrap auth function call(s) in policy 'Owner or team member can read mcp' on public.shared_mcp_configs so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Owner or team member can read mcp" ON public.shared_mcp_configs
    USING (owner_id = (SELECT auth.uid()) OR team_id IN (SELECT team_members.team_id FROM team_members WHERE team_members.user_id = auth.uid() AND team_members.status = CAST('active' AS text)));

-- [PERF001] Wrap auth function call(s) in policy 'Pro/Team users can create shared mcp' on public.shared_mcp_configs so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Pro/Team users can create shared mcp" ON public.shared_mcp_configs
    WITH CHECK (owner_id = (SELECT auth.uid()) AND user_has_plan((SELECT auth.uid()), ARRAY[CAST('pro' AS text), CAST('team' AS text)]));

-- [PERF001] Wrap auth function call(s) in policy 'Owner can delete their shared snippet' on public.shared_snippets so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Owner can delete their shared snippet" ON public.shared_snippets
    USING (owner_id = (SELECT auth.uid()));

-- [PERF001] Wrap auth function call(s) in policy 'Owner can update their shared snippet' on public.shared_snippets so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Owner can update their shared snippet" ON public.shared_snippets
    USING (owner_id = (SELECT auth.uid()));

-- [PERF001] Wrap auth function call(s) in policy 'Owner or team member can read snippet' on public.shared_snippets so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Owner or team member can read snippet" ON public.shared_snippets
    USING (owner_id = (SELECT auth.uid()) OR team_id IN (SELECT team_members.team_id FROM team_members WHERE team_members.user_id = auth.uid() AND team_members.status = CAST('active' AS text)));

-- [PERF001] Wrap auth function call(s) in policy 'Pro/Team users can create shared snippets' on public.shared_snippets so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Pro/Team users can create shared snippets" ON public.shared_snippets
    WITH CHECK (owner_id = (SELECT auth.uid()) AND user_has_plan((SELECT auth.uid()), ARRAY[CAST('pro' AS text), CAST('team' AS text)]));

-- [PERF001] Wrap auth function call(s) in policy 'Owner can delete their shared workspace' on public.shared_workspaces so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Owner can delete their shared workspace" ON public.shared_workspaces
    USING (owner_id = (SELECT auth.uid()));

-- [PERF001] Wrap auth function call(s) in policy 'Owner can update their shared workspace' on public.shared_workspaces so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Owner can update their shared workspace" ON public.shared_workspaces
    USING (owner_id = (SELECT auth.uid()));

-- [PERF001] Wrap auth function call(s) in policy 'Owner or team member can read workspace' on public.shared_workspaces so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Owner or team member can read workspace" ON public.shared_workspaces
    USING (owner_id = (SELECT auth.uid()) OR team_id IN (SELECT team_members.team_id FROM team_members WHERE team_members.user_id = auth.uid() AND team_members.status = CAST('active' AS text)));

-- [PERF001] Wrap auth function call(s) in policy 'Pro/Team users can create shared workspaces' on public.shared_workspaces so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Pro/Team users can create shared workspaces" ON public.shared_workspaces
    WITH CHECK (owner_id = (SELECT auth.uid()) AND user_has_plan((SELECT auth.uid()), ARRAY[CAST('pro' AS text), CAST('team' AS text)]));

-- [PERF001] Wrap auth function call(s) in policy 'Authors can delete own messages' on public.team_chat_messages so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Authors can delete own messages" ON public.team_chat_messages
    USING (user_id = (SELECT auth.uid()));

-- [PERF001] Wrap auth function call(s) in policy 'Team members can post messages' on public.team_chat_messages so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Team members can post messages" ON public.team_chat_messages
    WITH CHECK (user_id = (SELECT auth.uid()) AND team_id IN (SELECT team_members.team_id FROM team_members WHERE team_members.user_id = auth.uid() AND team_members.status = CAST('active' AS text)));

-- [PERF001] Wrap auth function call(s) in policy 'Team members can add reactions' on public.team_chat_reactions so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Team members can add reactions" ON public.team_chat_reactions
    WITH CHECK (user_id = (SELECT auth.uid()) AND team_id IN (SELECT team_members.team_id FROM team_members WHERE team_members.user_id = auth.uid() AND team_members.status = CAST('active' AS text)));

-- [PERF001] Wrap auth function call(s) in policy 'Users can remove own reactions' on public.team_chat_reactions so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can remove own reactions" ON public.team_chat_reactions
    USING (user_id = (SELECT auth.uid()));

-- [PERF001] Wrap auth function call(s) in policy 'Invitee can accept invitation' on public.team_members so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Invitee can accept invitation" ON public.team_members
    USING ((user_id = (SELECT auth.uid()) OR email = _current_user_email()) AND status = CAST('pending' AS text));

-- [PERF001] Wrap auth function call(s) in policy 'Invitee can decline own pending invite' on public.team_members so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Invitee can decline own pending invite" ON public.team_members
    USING (status = CAST('pending' AS text) AND (user_id = (SELECT auth.uid()) OR email = _current_user_email()));

-- [PERF001] Wrap auth function call(s) in policy 'Owner can manage member rows' on public.team_members so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Owner can manage member rows" ON public.team_members
    USING (user_id = (SELECT auth.uid()) OR team_id IN (SELECT _user_owned_team_ids() AS _user_owned_team_ids));

-- [PERF001] Wrap auth function call(s) in policy 'Team leader can delete members' on public.team_members so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Team leader can delete members" ON public.team_members
    USING (team_id IN (SELECT team_members_1.team_id FROM team_members AS team_members_1 WHERE team_members_1.user_id = auth.uid() AND team_members_1.role = CAST('leader' AS text) AND team_members_1.status = CAST('active' AS text)) AND user_id <> (SELECT teams.owner_id FROM teams WHERE teams.id = team_members.team_id) AND user_id <> (SELECT auth.uid()));

-- [PERF001] Wrap auth function call(s) in policy 'Team members can read member list' on public.team_members so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Team members can read member list" ON public.team_members
    USING (user_id = (SELECT auth.uid()) OR email = _current_user_email() OR team_id IN (SELECT _user_active_team_ids() AS _user_active_team_ids) OR team_id IN (SELECT _user_owned_team_ids() AS _user_owned_team_ids));

-- [PERF001] Wrap auth function call(s) in policy 'Team owner can invite' on public.team_members so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Team owner can invite" ON public.team_members
    WITH CHECK (invited_by = (SELECT auth.uid()) AND team_id IN (SELECT _user_owned_team_ids() AS _user_owned_team_ids));

-- [PERF001] Wrap auth function call(s) in policy 'User can cancel own join request' on public.team_members so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "User can cancel own join request" ON public.team_members
    USING (user_id = (SELECT auth.uid()) AND status = CAST('requested' AS text));

-- [PERF001] Wrap auth function call(s) in policy 'User can leave their team' on public.team_members so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "User can leave their team" ON public.team_members
    USING (user_id = (SELECT auth.uid()));

-- [PERF001] Wrap auth function call(s) in policy 'Users can manage their own repo paths' on public.team_repo_local_paths so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can manage their own repo paths" ON public.team_repo_local_paths
    USING ((SELECT auth.uid()) = user_id)
    WITH CHECK ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'Team leader can add repos' on public.team_repos so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Team leader can add repos" ON public.team_repos
    WITH CHECK (added_by = (SELECT auth.uid()) AND team_id IN (SELECT team_members.team_id FROM team_members WHERE team_members.user_id = auth.uid() AND team_members.role = CAST('leader' AS text) AND team_members.status = CAST('active' AS text)));

-- [PERF001] Wrap auth function call(s) in policy 'Owner can delete team' on public.teams so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Owner can delete team" ON public.teams
    USING (owner_id = (SELECT auth.uid()));

-- [PERF001] Wrap auth function call(s) in policy 'Owner can update team' on public.teams so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Owner can update team" ON public.teams
    USING (owner_id = (SELECT auth.uid()));

-- [PERF001] Wrap auth function call(s) in policy 'Team members can read their team' on public.teams so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Team members can read their team" ON public.teams
    USING (owner_id = (SELECT auth.uid()) OR _is_active_team_member(id) OR _user_has_pending_invite_to_team(id));

-- [PERF001] Wrap auth function call(s) in policy 'Team plan users can create teams' on public.teams so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Team plan users can create teams" ON public.teams
    WITH CHECK ((SELECT auth.uid()) = owner_id AND user_has_plan((SELECT auth.uid()), ARRAY[CAST('team' AS text)]));

-- [PERF001] Wrap auth function call(s) in policy 'Users can insert own preferences' on public.user_preferences so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can insert own preferences" ON public.user_preferences
    WITH CHECK ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'Users can read own preferences' on public.user_preferences so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can read own preferences" ON public.user_preferences
    USING ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'Users can update own preferences' on public.user_preferences so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can update own preferences" ON public.user_preferences
    USING ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'Pro/Team users can create their own repos' on public.user_repos so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Pro/Team users can create their own repos" ON public.user_repos
    WITH CHECK (user_id = (SELECT auth.uid()) AND user_has_plan((SELECT auth.uid()), ARRAY[CAST('pro' AS text), CAST('team' AS text)]));

-- [PERF001] Wrap auth function call(s) in policy 'Users can delete their own repos' on public.user_repos so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can delete their own repos" ON public.user_repos
    USING (user_id = (SELECT auth.uid()));

-- [PERF001] Wrap auth function call(s) in policy 'Users can read their own repos' on public.user_repos so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can read their own repos" ON public.user_repos
    USING (user_id = (SELECT auth.uid()));

-- [PERF001] Wrap auth function call(s) in policy 'Users can update their own repos' on public.user_repos so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can update their own repos" ON public.user_repos
    USING (user_id = (SELECT auth.uid()));
